schema:
  - https://graphql.datocms.com:
      headers:
        Authorization: "Bearer a199b061021fbedf349c9af50dacb1"
        X-Exclude-Invalid: "true"
documents: "./graphql/**/*.graphql"
generates:
  graphql/generated.ts:
    plugins:
      - typescript
      - typescript-operations:
          strictScalars: true
          scalars:
            BooleanType: boolean
            CustomData: Record<string, unknown>
            Date: string
            DateTime: string
            FloatType: number
            IntType: number
            ItemId: string
            JsonField: unknown
            MetaTagAttributes: Record<string, string>
            UploadId: string
      - typed-document-node
